apiVersion: apps/v1
kind: Deployment
metadata:
  name: tax-estimator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tax-estimator
  template:
    metadata:
      labels:
        app: tax-estimator
    spec:
      containers:
        - name: tax-estimator
          image: 924809052459.dkr.ecr.us-east-1.amazonaws.com/tax_estimator
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: tax-estimator-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: tax-estimator

# more to follow
