# port config for gateway
server:
    port: 8082

spring:
    data:
        mongodb:
                uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/?directConnection=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
                database: skillvestDB
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

    output:
        ansi:
            enabled: ALWAYS

    application:
        name: tax-service         # used as the id in the gateway routes
  

# configure where the discovery client is so our app can auto-register itself
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka.default.svc.cluster.local/eureka/}
  instance:
    preferIpAddress: true